#!/usr/bin/env python3
"""
generate_tables.py
Extracts empirical evaluation metrics from multiseed benchmark results
and generates publication-ready LaTeX tables for NeurIPS 2026.
Explicitly groups our 4-iteration method lineage (MARC -> COOP -> E-COOP -> THIEF)
separately from external baselines (MAPPO, H-MAPPO, COMA).
"""

import json
import os
from collections import defaultdict


def load_data(filepath=None):
    candidates = [
        filepath,
        "results/eval/eval_summary.json",
        "results/eval/multiseed_full_eval_n1000.json",
        "results/multiseed_summary.json",
    ]
    for p in candidates:
        if p and os.path.exists(p):
            try:
                with open(p, "r") as f:
                    return json.load(f)
            except Exception:  # noqa: BLE001, S112
                continue

    parquet_path = "results/stage_results.parquet"
    if filepath is None and os.path.exists(parquet_path):
        try:
            import polars as pl
            df = pl.read_parquet(parquet_path)
            return df.to_dicts()
        except Exception:  # noqa: BLE001, S110
            pass

    print("Warning: No benchmark evaluation results found.")
    return None

def generate_main_results_table(data, output_path="paper/tables/main_results.tex"):
    # Group: Ours (Lineage) vs External Baselines
    lineage = ["thief", "ecoop", "coop", "marc"]
    baselines = ["mappo", "hmappo", "coma"]
    external_role = ["roma", "rode"]
    all_algos = lineage + baselines + external_role

    stages = [0, 1, 2, 3, 4]
    
    grouped = defaultdict(lambda: defaultdict(list))
    if data is not None:
        for row in data:
            grouped[row["algo"]][row["stage"]].append(row)
            
    stats = {}
    for s in stages:
        max_wr = -1e9
        max_ret = -1e9
        for a in all_algos:
            runs = grouped[a][s]
            if runs:
                wrs = [r["win_rate"] * 100.0 for r in runs]
                rets = [r["mean_return"] for r in runs]
                wr_m = sum(wrs) / len(wrs)
                wr_s = (sum((x - wr_m)**2 for x in wrs)/(len(wrs)-1))**0.5 if len(wrs) > 1 else 0.0
                ret_m = sum(rets) / len(rets)
                ret_s = (sum((x - ret_m)**2 for x in rets)/(len(rets)-1))**0.5 if len(rets) > 1 else 0.0
                stats[(a, s)] = (wr_m, wr_s, ret_m, ret_s)
                max_wr = max(max_wr, wr_m)
                max_ret = max(max_ret, ret_m)
            else:
                stats[(a, s)] = None
        stats[("max", s)] = (max_wr, max_ret)

    stage_labels = [
        "St. 0 ($11\\times 11$)",
        "St. 1 ($17\\times 17$)",
        "St. 2 ($25\\times 25$)",
        "St. 3 ($35\\times 35$)",
        "St. 4 ($50\\times 50$)"
    ]

    table_content = [
        "% Auto-generated by paper/scripts/generate_tables.py. Do not edit manually.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Benchmark performance across five HEIST curriculum stages ($11\\times 11$ to $50\\times 50$). Reported as $\\text{mean} \\pm \\text{std}$ evaluated over $N=1,\\!000$ episodes across 10 random seeds ($10,\\!000$ episodes per cell, $450,\\!000$ total evaluation episodes across all nine algorithms under the identical protocol). Columns are partitioned into our iterative development lineage (MARC $\\to$ COOP $\\to$ E-COOP $\\to$ THIEF) versus five external MARL baselines. Bold denotes best performance overall.}",
        "\\label{tab:main_results}",
        "\\vspace{0.05in}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{ll cccc ccccc}",
        "\\toprule",
        " & & \\multicolumn{4}{c}{\\textbf{Iterative Method Lineage (Ours)}} & \\multicolumn{5}{c}{\\textbf{External Baselines}} \\\\",
        "\\cmidrule(lr){3-6} \\cmidrule(lr){7-11}",
        "\\textbf{Stage} & \\textbf{Metric} & \\textbf{THIEF (Final)} & \\textbf{E-COOP (Iter 3)} & \\textbf{COOP (Iter 2)} & \\textbf{MARC (Iter 1)} & \\textbf{MAPPO} & \\textbf{H-MAPPO} & \\textbf{COMA} & \\textbf{ROMA} & \\textbf{RODE} \\\\",
        "\\midrule"
    ]
    
    for s in stages:
        max_wr, max_ret = stats.get(("max", s), (-1e9, -1e9))
        
        # Row 1: Win rate
        wr_cells = []
        for a in all_algos:
            st = stats.get((a, s))
            if st is None:
                wr_cells.append("--")
            else:
                wr_m, wr_s = st[0], st[1]
                val_str = f"{wr_m:.1f}\\tiny$\\pm${wr_s:.1f}\\%"
                if abs(wr_m - max_wr) < 0.05:
                    val_str = f"\\textbf{{{val_str}}}"
                wr_cells.append(val_str)
        
        # Row 2: Return
        ret_cells = []
        for a in all_algos:
            st = stats.get((a, s))
            if st is None:
                ret_cells.append("--")
            else:
                ret_m, ret_s = st[2], st[3]
                val_str = f"{ret_m:.2f}\\tiny$\\pm${ret_s:.2f}"
                if abs(ret_m - max_ret) < 0.05:
                    val_str = f"\\textbf{{{val_str}}}"
                ret_cells.append(val_str)
                
        table_content.append(f"\\multirow{{2}}{{*}}{{{stage_labels[s]}}} & Win Rate & " + " & ".join(wr_cells) + " \\\\")
        table_content.append(" & Return & " + " & ".join(ret_cells) + " \\\\")
        if s < 4:
            table_content.append("\\midrule")
            
    table_content.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}",
        "\\end{table*}"
    ])
    
    # Fail-safe: if the available data does not cover every algorithm/stage cell,
    # do NOT overwrite an existing (complete) table with placeholder "--" cells.
    joined = "\n".join(table_content)
    if data is None or "-- &" in joined or "& --" in joined:
        if os.path.exists(output_path):
            with open(output_path) as f:
                existing = f.read()
            if "-- &" not in existing and "& --" not in existing:
                print(f"WARNING: incomplete evaluation data (missing algorithm/stage cells); "
                      f"keeping existing complete table at {output_path}")
                return
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(table_content) + "\n")
    print(f"Wrote main results table to {output_path}")

def generate_subtask_table(data, output_path="paper/tables/subtask_metrics.tex"):
    lineage = [
        ("thief", "\\textbf{THIEF (Ours, Final)}"),
        ("ecoop", "E-COOP (Iteration 3: Evo Crossover)"),
        ("coop",  "COOP (Iteration 2: Static MoE)"),
        ("marc",  "MARC (Iteration 1: Credit Shaping)"),
    ]
    baselines = [
        ("mappo",  "MAPPO (Centralized PPO Baseline)"),
        ("hmappo", "H-MAPPO (Hierarchical Baseline)"),
        ("coma",   "COMA (Counterfactual Baseline)"),
    ]
    
    grouped = defaultdict(lambda: defaultdict(list))
    if data is not None:
        for row in data:
            grouped[row["algo"]][row["stage"]].append(row)
            
    table_content = [
        "% Auto-generated by paper/scripts/generate_tables.py. Do not edit manually.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Role subtask completion rates and tactical telemetry on Stage 3 ($35\\times 35$, 3 guards, 2 cameras, 3 locked doors). Evaluation over $N=1,\\!000$ episodes across 10 random seeds ($10,\\!000$ episodes total per algorithm). Partitioned into our iterative development lineage versus external baselines. Bold denotes highest completion rate or lowest alarm overall.}",
        "\\label{tab:subtasks_stage3}",
        "\\vspace{0.05in}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{l ccccc cc}",
        "\\toprule",
        "\\textbf{Method} & \\textbf{Scout Tag} & \\textbf{Hacker Hack} & \\textbf{Muscle Neut.} & \\textbf{Extractor Loot} & \\textbf{Agents Ext.} & \\textbf{Mean Alarm} & \\textbf{Mean Steps} \\\\",
        " & (\\%) & (\\%) & (\\%) & (\\%) & (out of 4) & (max 150) & (max 2,000) \\\\",
        "\\midrule",
        "\\multicolumn{8}{l}{\\textit{\\textbf{Proposed Method Lineage (Ours)}}} \\\\",
        "\\midrule"
    ]
    
    all_keys = [k for k, _ in lineage] + [k for k, _ in baselines]
    stage_runs = {a: grouped[a][3] for a in all_keys if grouped[a][3]}
    bests = {}
    if stage_runs:
        for metric in ["scout_tag_rate", "hacker_hack_rate", "muscle_neutralize_rate", "extractor_loot_rate", "avg_agents_extract"]:
            bests[metric] = max(sum(r.get(metric, 0.0) for r in stage_runs[a])/len(stage_runs[a]) for a in stage_runs)
        bests["avg_alarm"] = min(sum(r.get("avg_alarm", 0.0) for r in stage_runs[a])/len(stage_runs[a]) for a in stage_runs)
    else:
        for metric in ["scout_tag_rate", "hacker_hack_rate", "muscle_neutralize_rate", "extractor_loot_rate", "avg_agents_extract"]:
            bests[metric] = 0.0
        bests["avg_alarm"] = 0.0
    
    def format_rows(algo_list):
        rows = []
        for a, name in algo_list:
            runs = grouped[a][3]
            if not runs:
                rows.append(f"{name} & -- & -- & -- & -- & -- & -- & -- \\\\")
                continue
            n = len(runs)
            tag = sum(r["scout_tag_rate"] * 100 for r in runs) / n
            hack = sum(r["hacker_hack_rate"] * 100 for r in runs) / n
            neut = sum(r["muscle_neutralize_rate"] * 100 for r in runs) / n
            loot = sum(r["extractor_loot_rate"] * 100 for r in runs) / n
            ext = sum(r["avg_agents_extract"] for r in runs) / n
            alarm = sum(r["avg_alarm"] for r in runs) / n
            steps = sum(r["avg_steps"] for r in runs) / n
            
            tag_s = f"{tag:.1f}\\%" if tag < bests["scout_tag_rate"]*100 - 0.05 else f"\\textbf{{{tag:.1f}\\%}}"
            hack_s = f"{hack:.1f}\\%" if hack < bests["hacker_hack_rate"]*100 - 0.05 else f"\\textbf{{{hack:.1f}\\%}}"
            neut_s = f"{neut:.1f}\\%" if neut < bests["muscle_neutralize_rate"]*100 - 0.05 else f"\\textbf{{{neut:.1f}\\%}}"
            loot_s = f"{loot:.1f}\\%" if loot < bests["extractor_loot_rate"]*100 - 0.05 else f"\\textbf{{{loot:.1f}\\%}}"
            ext_s = f"{ext:.2f}" if ext < bests["avg_agents_extract"] - 0.02 else f"\\textbf{{{ext:.2f}}}"
            alarm_s = f"{alarm:.1f}" if alarm > bests["avg_alarm"] + 0.05 else f"\\textbf{{{alarm:.1f}}}"
            steps_s = f"{steps:.1f}"
            
            rows.append(f"{name} & {tag_s} & {hack_s} & {neut_s} & {loot_s} & {ext_s} & {alarm_s} & {steps_s} \\\\")
        return rows

    table_content.extend(format_rows(lineage))
    table_content.extend([
        "\\midrule",
        "\\multicolumn{8}{l}{\\textit{\\textbf{External MARL Baselines}}} \\\\",
        "\\midrule"
    ])
    table_content.extend(format_rows(baselines))
    table_content.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}",
        "\\end{table*}"
    ])
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(table_content) + "\n")
    print(f"Wrote subtask metrics table to {output_path}")

if __name__ == "__main__":
    eval_data = load_data()
    generate_main_results_table(eval_data)
    generate_subtask_table(eval_data)
