#!/usr/bin/env python3
"""
generate_ablation_table.py
Builds the LaTeX micro-ablation table for THIEF from:
  * results/eval/ablation_<variant>_eval_n<episodes>.json   (held-out win rates)
  * results/ablation/<variant>/thief/seed_<s>/stage_<x>/results.json (mechanism metrics)

One row per ablation variant: held-out win rate per stage (mean +- std across
training seeds) plus mechanism telemetry aggregated across seeds and stages.
"""

import argparse
import glob
import json
import os
from collections import defaultdict

import numpy as np

VARIANT_META = {
    "none":           ("Full THIEF", "nothing ablated"),
    "no_incubation":  ("w/o incubation", r"$\tau_{\mathrm{iso}}=0$ (child skips sandbox)"),
    "uniform_recomb": ("w/o Fisher geometry", "uniform recombination"),
    "clone_best":     ("clone-best-parent", r"child $=$ best parent $+$ noise"),
    "no_balance":     (r"w/o load balancing", r"$\alpha_{\mathrm{bal}}=0$"),
    "no_hysteresis":  ("w/o hysteresis", r"$\epsilon=0$"),
    "fixed_schedule": ("fixed-schedule spawning", "plateau trigger bypassed"),
}

VARIANT_ORDER = [
    "none",
    "no_incubation",
    "uniform_recomb",
    "clone_best",
    "no_balance",
    "no_hysteresis",
    "fixed_schedule",
]

STAGE_LABELS = {2: r"Stage 2 ($25^2$)", 4: r"Stage 4 ($50^2$)"}


def load_eval(variant, episodes):
    path = f"results/eval/ablation_{variant}_eval_n{episodes}.json"
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def load_mechanism_metrics(variant):
    """Aggregate mechanism telemetry from per-run results.json files."""
    rows = sorted(glob.glob(f"results/ablation/{variant}/thief/seed_*/stage_*/results.json"))
    spawns, switches, entropies, actives = [], [], [], []
    for path in rows:
        with open(path) as f:
            r = json.load(f)
        spawns.append(r.get("total_spawns", 0))
        actives.append(r.get("active_experts", 1))
        ent = r.get("routing_entropy_nats")
        if ent is not None and ent == ent:  # skip NaN
            entropies.append(ent)
        sw = r.get("expert_switch_rate")
        if sw is not None:
            switches.append(sw)
    return {
        "spawns": float(np.mean(spawns)) if spawns else None,
        "switch_rate": float(np.mean(switches)) if switches else None,
        "entropy": float(np.mean(entropies)) if entropies else None,
        "active": float(np.mean(actives)) if actives else None,
    }


def wr_cell(mean, std, best_mean):
    if mean is None:
        return "--"
    text = f"{mean:.1f}\\tiny$\\pm${std:.1f}\\%"
    if best_mean is not None and abs(mean - best_mean) < 0.05:
        text = f"\\textbf{{{text}}}"
    return text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--episodes", type=int, default=1000)
    args = ap.parse_args()

    # ---- Load eval results -------------------------------------------------
    raw = {}
    for variant in VARIANT_ORDER:
        data = load_eval(variant, args.episodes)
        if data:
            raw[variant] = data
        else:
            print(f"[warn] no eval data for '{variant}' -- row will be omitted")
    if not raw:
        print("No ablation evaluation data found. Run paper/scripts/run_ablation_suite.sh first.")
        return

    stages = sorted({row["stage"] for data in raw.values() for row in data})

    # ---- Aggregate win rates over seeds ------------------------------------
    agg = defaultdict(dict)
    for variant, data in raw.items():
        by_stage = defaultdict(list)
        for row in data:
            by_stage[row["stage"]].append(row["win_rate"] * 100.0)
        for stage, vals in by_stage.items():
            agg[variant][stage] = (
                float(np.mean(vals)),
                float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0,
            )

    best = {}
    for stage in stages:
        candidates = [agg[v][stage][0] for v in raw if stage in agg[v]]
        best[stage] = max(candidates) if candidates else None

    # ---- Emit table --------------------------------------------------------
    lines = [
        "% Auto-generated by paper/scripts/generate_ablation_table.py. Do not edit manually.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Component micro-ablations of THIEF, trained standalone (fresh initialization, no curriculum transfer) on the diagnostic stages with identical per-stage budgets, then evaluated over $N=1,\\!000$ held-out episodes per seed. Mechanism telemetry is averaged across seeds and stages. Bold denotes the best held-out win rate per stage.}",
        "\\label{tab:ablations}",
        "\\vspace{0.05in}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{l l cc ccc}",
        "\\toprule",
        " & & \\multicolumn{2}{c}{\\textbf{Held-out win rate (\\%)}} & \\multicolumn{3}{c}{\\textbf{Mechanism telemetry}} \\\\",
        "\\cmidrule(lr){3-4} \\cmidrule(lr){5-7}",
        "\\textbf{Variant} & \\textbf{Ablated component} & "
        + " & ".join(STAGE_LABELS.get(s, f"Stage {s}") for s in stages)
        + " & Spawns & Switch (\\%) & $H(f)$ (nats) \\\\",
        "\\midrule",
    ]

    for variant in VARIANT_ORDER:
        if variant not in raw:
            continue
        name, desc = VARIANT_META[variant]
        cells = [wr_cell(*agg[variant].get(s, (None, None)), best.get(s)) for s in stages]

        mech = load_mechanism_metrics(variant)
        sp = f"{mech['spawns']:.1f}" if mech["spawns"] is not None else "--"
        sw = f"{mech['switch_rate']:.1f}" if mech["switch_rate"] is not None else "--"
        en = f"{mech['entropy']:.2f}" if mech["entropy"] is not None else "--"

        lines.append(f"{name} & {desc} & " + " & ".join(cells) + f" & {sp} & {sw} & {en} \\\\")

    lines.extend(["\\bottomrule", "\\end{tabular}", "}", "\\end{table*}"])

    os.makedirs("paper/tables", exist_ok=True)
    with open("paper/tables/ablation.tex", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote paper/tables/ablation.tex")


if __name__ == "__main__":
    main()